### ISSUE TITLE
507. Perfect Number, use Look-up table method

### ISSUE THREAD

**Issue by ajinwu** [cy69855522/Shortest-LeetCode-Python-Solutions#10]
``` python
class Solution:
    def checkPerfectNumber(self, num: int) -> bool:
        perfect = [6, 28, 496, 8128, 33550336, 8589869056, 137438691328, 2305843008139952128]
        if num in perfect:
            return True
        return False
```

**Comment by cy69855522** [comment]
Thank you for your method, look-up table is a good skill in the competition, but I don't think the method of listing the answers is suitable for this question. There are countless answers to this question, and AC is simply because there are not enough leetcode test cases. So this is not a strictly correct solution unless we can prove that the number of solutions to the problem is finite. What do you think?

**Comment by ajinwu** [comment]
[let see it](https://zh.m.wikipedia.org/zh/%E5%AE%8C%E5%85%A8%E6%95%B0), in Wikipedia, this answer is ten, in the current computer, has 54 bit is very difficult, so this answer in the normal computer is limited, so I think it can be used, thanks for you answer, my English is not good.

**Comment by cy69855522** [comment]
Oh, you're right.And I noticed that the range of Numbers was given in the question, which I think is a good idea. Thank you for your reply.
